### ISSUE TITLE
Headers missing in release zip

### ISSUE THREAD

**Issue by daviel** [Daniels118/blackandwhite#19]
Hey,

thank you very much for the tool! I am currently using it and it is working perfect for me so far. :)

I saw that there is something off with the 0.2 release. The headers path is missing in the zip file. Not a big thing but I had to download the whole repo to get the headers and putting them in the extracted path.

**Comment by Daniels118** [comment]
Thank you for reporting this issue, with commit 057b7f4 I have updated the ant build script to include the headers folder. I have replaced the zip of release 0.2, now headers are included.
