### ISSUE TITLE
Headers enum last line with comma lead to error on compilation

### ISSUE THREAD

**Issue by daviel** [Daniels118/blackandwhite#20]
Hey,

I replaced my local 0.2 release of your tool with the one you released a few days ago. Unfortunately this led to new problems occurring for me. See the command below:

```
java -cp chlasm.jar it.ld.bw.chl.Main '%*' -compile -p samples/sample1/_project.txt -o test.chl -v
loading AudioMusic.h...
Redefinition of constant  with different value at AudioMusic.h:120:1
```

I could fix it by removing the trailing comma at the end of the enum definition which is weird as it was working perfectly fine before. 

But afterwards I received this message:

```
java -cp chlasm.jar it.ld.bw.chl.Main '%*' -compile -p samples/sample1/_project.txt -o test.chl -v
loading AudioMusic.h...
loading AudioSFX.h...
loading CameraPosEnum.h...
loading CreatureEnum.h...
loading CreatureSpec.h...
loading GStates.h...
loading HitRegions.h...
loading LHSample.h...
loading ScriptChallengeEnums.h...
loading ScriptEnums.h...
loading ScriptEnumstwo.h...
loading info1.txt...
loading info2.txt...
loading InfoScript1.txt...
loading _constants.txt...
Redefinition of constant CHALLENGE_LandControl3 with different value at _constants.txt:9:1
```

The constant is set in two different files but I am not sure where it should reside in the end. 

I tried it on ubuntu 20.04+java 11 and also on Mac OS 14.5+Java 11 with the same results.

**Comment by Daniels118** [comment]
I have found these problems while implementing the new feature, I completely forgot that I had pending changes made after release 0.2. The old working v0.2 is lost forever, but at least I have fixed all bugs in v 0.3 (commit #54964c2).

Thank you for reporting!
